### ISSUE TITLE
Compile error: Resolution failed for 1 modules:

### ISSUE THREAD

**Issue by ilongshan** [chipsalliance/rocket#24]
I am tring to compile it with the following commands:
```
git clone git@github.com:chipsalliance/rocket.git
cd rocket
make init
make compile
```
But I got errors:
```
mill -i -j 0 __.compile
Preparing Java 20.0.1 runtime; this may take a minute or two ...
[build.sc] [#5] [35/49] resolvedRunIvyDeps | Downloading [2/2] artifacts (~0/554 bytes)
2 targets failed
resolvedIvyDeps
Resolution failed for 1 modules:
--------------------------------------------
  de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11_2.13:0.3.0
	not found: /Users/Test/.ivy2/local/de.tototec/de.tobiasroeser.mill.vcs.version_mill0.11_2.13/0.3.0/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.vcs.version_mill0.11_2.13/0.3.0/de.tobiasroeser.mill.vcs.version_mill0.11_2.13-0.3.0.pom

--------------------------------------------

For additional information on library dependencies, see the docs at
https://mill-build.com/mill/Library_Dependencies.html

resolvedRunIvyDeps
Resolution failed for 1 modules:
--------------------------------------------
  de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11_2.13:0.3.0
	not found: /Users/Test/.ivy2/local/de.tototec/de.tobiasroeser.mill.vcs.version_mill0.11_2.13/0.3.0/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/de/tototec/de.tobiasroeser.mill.vcs.version_mill0.11_2.13/0.3.0/de.tobiasroeser.mill.vcs.version_mill0.11_2.13-0.3.0.pom

--------------------------------------------

For additional information on library dependencies, see the docs at
https://mill-build.com/mill/Library_Dependencies.html
```

How to resolve it and how to compile this project?

**Comment by QL1115** [comment]
@ilongshan 
Hi, I encountered the same question as yours, I tried some solutions and solved it.
It seems that  mill version 0.11_2.13 is not correct, I tried mill version 0.10.0, and this error was solved.

Here are some issues I met and my solutions.

1. **Install mill 0.10.0**
    ```shell
    # Ubuntu 20.04
    sudo sh -c "curl -L https://github.com/com-lihaoyi/mill/releases/download/0.10.0/0.10.0 > /usr/local/bin/mill && chmod +x /usr/local/bin/mill"
    ```

2. **Install antlr4**
    After downloading mill 0.10.0, and rerun `make compile`, you may encounter a new issue 
    ```shell
    Exception in thread "main" java.lang.reflect.InvocationTargetException
    #......
    Caused by: java.io.IOException: Cannot run program "antlr4"
    #...
    ```
    Just downlaod antlr4
    ```shell
    # download antlr4
    sudo apt-get update
    sudo apt-get install antlr4
    ```

3. **set RISCV_TESTS_ROOT variable**
    After I reran `make compile`, it told me I not set variable RISCV_TESTS_ROOT.
    I saw that riscvtests in build.sc will find rv32 and rv64 isa tests under $RISCV_TESTS_ROOT/share/riscv-tests folder.
    Just download those tests and set variable, then rerun `make compile`

4. **(Optional) Change LLVM-Clang to GCC** 
    Because I use GNU riscv toolchain, so I change LLVM-Clang to GNU riscv toolchain in build.sc

I hope this is useful to you.

All the best,
QL Chiang

**Comment by ilongshan** [comment]
@QL1115 
Thanks for your instructions. Based on your instructions and with some hacking, finally I can make it to compile and loaded to IDEA to navigate the code.
